# Generated by Django 2.2.7 on 2019-11-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('duracion', models.CharField(max_length=10)),
                ('orden', models.CharField(max_length=100)),
            ],
        ),
    ]
