# Generated by Django 2.2.7 on 2019-11-22 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albumes', '0001_initial'),
        ('canciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='albumes.Album'),
            preserve_default=False,
        ),
    ]
