# Generated by Django 2.2.7 on 2019-11-22 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canciones', '0002_cancion_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='album',
        ),
    ]
